# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-13 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checksum', models.CharField(db_index=True, max_length=40, unique=True)),
                ('project_id', models.PositiveIntegerField(db_index=True)),
                ('issue_id', models.PositiveIntegerField(db_index=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
